name: INVESTMENT NEWSROOM
favicon: null
layout_spectrum: 0.8306435784325004
typography_spectrum: 0.5207220281008631
title: INVESTMENT NEWSROOM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8360087967012078
  lightness: 0.19684901367872953
  saturation: 0.22597214044071734
  rhythmicContrast: 0.24650613754056394
purpose: []
